name: flutter_forwards
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^1.10.18
  provider: ^6.0.5
  flutter_dotenv: ^5.1.0
  freezed_annotation: ^2.4.1
  fl_chart: ^0.63.0
  collection: ^1.17.1
  intl: ^0.18.1
  percent_indicator: ^4.2.3
  http: ^1.1.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  freezed: ^2.4.3
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:  
  uses-material-design: true
  assets:
    - .env